package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BaseUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.USER_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.PASSWORD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.HEAD_ICO_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String headIcoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.NICKNAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.MOBILE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.TEL_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String telNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.EMAIL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.SEX_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String sexId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.REALNAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.QQ
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.WEICHAT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String weichat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.STATUS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.DEPARTMENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer markDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.ID
     *
     * @return the value of base_user.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.ID
     *
     * @param id the value for base_user.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.USER_NAME
     *
     * @return the value of base_user.USER_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.USER_NAME
     *
     * @param userName the value for base_user.USER_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.PASSWORD
     *
     * @return the value of base_user.PASSWORD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.PASSWORD
     *
     * @param password the value for base_user.PASSWORD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.TYPE
     *
     * @return the value of base_user.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.TYPE
     *
     * @param type the value for base_user.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.HEAD_ICO_ID
     *
     * @return the value of base_user.HEAD_ICO_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getHeadIcoId() {
        return headIcoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.HEAD_ICO_ID
     *
     * @param headIcoId the value for base_user.HEAD_ICO_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setHeadIcoId(String headIcoId) {
        this.headIcoId = headIcoId == null ? null : headIcoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.NICKNAME
     *
     * @return the value of base_user.NICKNAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.NICKNAME
     *
     * @param nickname the value for base_user.NICKNAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.MOBILE
     *
     * @return the value of base_user.MOBILE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.MOBILE
     *
     * @param mobile the value for base_user.MOBILE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.TEL_NUMBER
     *
     * @return the value of base_user.TEL_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTelNumber() {
        return telNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.TEL_NUMBER
     *
     * @param telNumber the value for base_user.TEL_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTelNumber(String telNumber) {
        this.telNumber = telNumber == null ? null : telNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.EMAIL
     *
     * @return the value of base_user.EMAIL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.EMAIL
     *
     * @param email the value for base_user.EMAIL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.SEX_ID
     *
     * @return the value of base_user.SEX_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getSexId() {
        return sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.SEX_ID
     *
     * @param sexId the value for base_user.SEX_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setSexId(String sexId) {
        this.sexId = sexId == null ? null : sexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.REALNAME
     *
     * @return the value of base_user.REALNAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.REALNAME
     *
     * @param realname the value for base_user.REALNAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.ADDRESS
     *
     * @return the value of base_user.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.ADDRESS
     *
     * @param address the value for base_user.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.QQ
     *
     * @return the value of base_user.QQ
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.QQ
     *
     * @param qq the value for base_user.QQ
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.WEICHAT
     *
     * @return the value of base_user.WEICHAT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getWeichat() {
        return weichat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.WEICHAT
     *
     * @param weichat the value for base_user.WEICHAT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setWeichat(String weichat) {
        this.weichat = weichat == null ? null : weichat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.STATUS
     *
     * @return the value of base_user.STATUS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.STATUS
     *
     * @param status the value for base_user.STATUS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.DEPARTMENT_ID
     *
     * @return the value of base_user.DEPARTMENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.DEPARTMENT_ID
     *
     * @param departmentId the value for base_user.DEPARTMENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.DUTY
     *
     * @return the value of base_user.DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.DUTY
     *
     * @param duty the value for base_user.DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.CREATION_TIME
     *
     * @return the value of base_user.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.CREATION_TIME
     *
     * @param creationTime the value for base_user.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.CREATION_USER_ID
     *
     * @return the value of base_user.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.CREATION_USER_ID
     *
     * @param creationUserId the value for base_user.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.LAST_UPDATE_TIME
     *
     * @return the value of base_user.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for base_user.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.LAST_UPDATE_USER_ID
     *
     * @return the value of base_user.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for base_user.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.DELETE_TIME
     *
     * @return the value of base_user.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.DELETE_TIME
     *
     * @param deleteTime the value for base_user.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.DELETE_USER_ID
     *
     * @return the value of base_user.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.DELETE_USER_ID
     *
     * @param deleteUserId the value for base_user.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId == null ? null : deleteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.MARK_DELETE
     *
     * @return the value of base_user.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.MARK_DELETE
     *
     * @param markDelete the value for base_user.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }
}