package com.yuanchuangyun.libra.model;

public class BasePermissionResourceRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission_resource_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission_resource_rel.PERMISSION_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_permission_resource_rel.RESOURCE_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission_resource_rel.ID
     *
     * @return the value of base_permission_resource_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission_resource_rel.ID
     *
     * @param id the value for base_permission_resource_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission_resource_rel.PERMISSION_ID
     *
     * @return the value of base_permission_resource_rel.PERMISSION_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission_resource_rel.PERMISSION_ID
     *
     * @param permissionId the value for base_permission_resource_rel.PERMISSION_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_permission_resource_rel.RESOURCE_ID
     *
     * @return the value of base_permission_resource_rel.RESOURCE_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_permission_resource_rel.RESOURCE_ID
     *
     * @param resourceId the value for base_permission_resource_rel.RESOURCE_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }
}