package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BaseRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_role.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer markDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.ID
     *
     * @return the value of base_role.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.ID
     *
     * @param id the value for base_role.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.NAME
     *
     * @return the value of base_role.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.NAME
     *
     * @param name the value for base_role.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.CODE
     *
     * @return the value of base_role.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.CODE
     *
     * @param code the value for base_role.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.TYPE
     *
     * @return the value of base_role.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.TYPE
     *
     * @param type the value for base_role.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.DESCRIPTION
     *
     * @return the value of base_role.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.DESCRIPTION
     *
     * @param description the value for base_role.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.ORDER_NO
     *
     * @return the value of base_role.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.ORDER_NO
     *
     * @param orderNo the value for base_role.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.CREATION_TIME
     *
     * @return the value of base_role.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.CREATION_TIME
     *
     * @param creationTime the value for base_role.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.CREATION_USER_ID
     *
     * @return the value of base_role.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.CREATION_USER_ID
     *
     * @param creationUserId the value for base_role.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.LAST_UPDATE_TIME
     *
     * @return the value of base_role.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for base_role.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.LAST_UPDATE_USER_ID
     *
     * @return the value of base_role.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for base_role.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.DELETE_TIME
     *
     * @return the value of base_role.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.DELETE_TIME
     *
     * @param deleteTime the value for base_role.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.DELETE_USER_ID
     *
     * @return the value of base_role.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.DELETE_USER_ID
     *
     * @param deleteUserId the value for base_role.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId == null ? null : deleteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_role.MARK_DELETE
     *
     * @return the value of base_role.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_role.MARK_DELETE
     *
     * @param markDelete the value for base_role.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }
}