package com.yuanchuangyun.libra.model;

public class BizApplicant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String nameCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.NAME_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String nameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String nameOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.ADDRESS_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String addressCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.ADDRESS_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String addressEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.ADDRESS_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String addressOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.DEPUTY_NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deputyNameCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.DEPUTY_NAME_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deputyNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.DEPUTY_NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deputyNameOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.DEPUTY_DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deputyDuty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.IDENTIFICATION_CARD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String identificationCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.ORGANIZATION_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String organizationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.IDENTIFICATION_LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String identificationLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_applicant.BUSINESS_LICENCE_LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String businessLicenceLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.ID
     *
     * @return the value of biz_applicant.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.ID
     *
     * @param id the value for biz_applicant.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.NAME_CH
     *
     * @return the value of biz_applicant.NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getNameCh() {
        return nameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.NAME_CH
     *
     * @param nameCh the value for biz_applicant.NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setNameCh(String nameCh) {
        this.nameCh = nameCh == null ? null : nameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.NAME_EN
     *
     * @return the value of biz_applicant.NAME_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.NAME_EN
     *
     * @param nameEn the value for biz_applicant.NAME_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.NAME_ORIGINAL
     *
     * @return the value of biz_applicant.NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getNameOriginal() {
        return nameOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.NAME_ORIGINAL
     *
     * @param nameOriginal the value for biz_applicant.NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setNameOriginal(String nameOriginal) {
        this.nameOriginal = nameOriginal == null ? null : nameOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.ADDRESS_CH
     *
     * @return the value of biz_applicant.ADDRESS_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddressCh() {
        return addressCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.ADDRESS_CH
     *
     * @param addressCh the value for biz_applicant.ADDRESS_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddressCh(String addressCh) {
        this.addressCh = addressCh == null ? null : addressCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.ADDRESS_EN
     *
     * @return the value of biz_applicant.ADDRESS_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddressEn() {
        return addressEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.ADDRESS_EN
     *
     * @param addressEn the value for biz_applicant.ADDRESS_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddressEn(String addressEn) {
        this.addressEn = addressEn == null ? null : addressEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.ADDRESS_ORIGINAL
     *
     * @return the value of biz_applicant.ADDRESS_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddressOriginal() {
        return addressOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.ADDRESS_ORIGINAL
     *
     * @param addressOriginal the value for biz_applicant.ADDRESS_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddressOriginal(String addressOriginal) {
        this.addressOriginal = addressOriginal == null ? null : addressOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.DEPUTY_NAME_CH
     *
     * @return the value of biz_applicant.DEPUTY_NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeputyNameCh() {
        return deputyNameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.DEPUTY_NAME_CH
     *
     * @param deputyNameCh the value for biz_applicant.DEPUTY_NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeputyNameCh(String deputyNameCh) {
        this.deputyNameCh = deputyNameCh == null ? null : deputyNameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.DEPUTY_NAME_EN
     *
     * @return the value of biz_applicant.DEPUTY_NAME_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeputyNameEn() {
        return deputyNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.DEPUTY_NAME_EN
     *
     * @param deputyNameEn the value for biz_applicant.DEPUTY_NAME_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeputyNameEn(String deputyNameEn) {
        this.deputyNameEn = deputyNameEn == null ? null : deputyNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.DEPUTY_NAME_ORIGINAL
     *
     * @return the value of biz_applicant.DEPUTY_NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeputyNameOriginal() {
        return deputyNameOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.DEPUTY_NAME_ORIGINAL
     *
     * @param deputyNameOriginal the value for biz_applicant.DEPUTY_NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeputyNameOriginal(String deputyNameOriginal) {
        this.deputyNameOriginal = deputyNameOriginal == null ? null : deputyNameOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.DEPUTY_DUTY
     *
     * @return the value of biz_applicant.DEPUTY_DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeputyDuty() {
        return deputyDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.DEPUTY_DUTY
     *
     * @param deputyDuty the value for biz_applicant.DEPUTY_DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeputyDuty(String deputyDuty) {
        this.deputyDuty = deputyDuty == null ? null : deputyDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.TYPE
     *
     * @return the value of biz_applicant.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.TYPE
     *
     * @param type the value for biz_applicant.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.IDENTIFICATION_CARD
     *
     * @return the value of biz_applicant.IDENTIFICATION_CARD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIdentificationCard() {
        return identificationCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.IDENTIFICATION_CARD
     *
     * @param identificationCard the value for biz_applicant.IDENTIFICATION_CARD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIdentificationCard(String identificationCard) {
        this.identificationCard = identificationCard == null ? null : identificationCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.ORGANIZATION_CODE
     *
     * @return the value of biz_applicant.ORGANIZATION_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.ORGANIZATION_CODE
     *
     * @param organizationCode the value for biz_applicant.ORGANIZATION_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.IDENTIFICATION_LOCATION
     *
     * @return the value of biz_applicant.IDENTIFICATION_LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIdentificationLocation() {
        return identificationLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.IDENTIFICATION_LOCATION
     *
     * @param identificationLocation the value for biz_applicant.IDENTIFICATION_LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIdentificationLocation(String identificationLocation) {
        this.identificationLocation = identificationLocation == null ? null : identificationLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_applicant.BUSINESS_LICENCE_LOCATION
     *
     * @return the value of biz_applicant.BUSINESS_LICENCE_LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getBusinessLicenceLocation() {
        return businessLicenceLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_applicant.BUSINESS_LICENCE_LOCATION
     *
     * @param businessLicenceLocation the value for biz_applicant.BUSINESS_LICENCE_LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setBusinessLicenceLocation(String businessLicenceLocation) {
        this.businessLicenceLocation = businessLicenceLocation == null ? null : businessLicenceLocation.trim();
    }
}