package com.yuanchuangyun.libra.model;

public class BizAgency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_agency.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_agency.AREA
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_agency.ORGANIZATION_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String organizationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_agency.ORGANIZATION_NAME_ABBR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String organizationNameAbbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_agency.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_agency.ID
     *
     * @return the value of biz_agency.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_agency.ID
     *
     * @param id the value for biz_agency.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_agency.AREA
     *
     * @return the value of biz_agency.AREA
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_agency.AREA
     *
     * @param area the value for biz_agency.AREA
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_agency.ORGANIZATION_NAME
     *
     * @return the value of biz_agency.ORGANIZATION_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_agency.ORGANIZATION_NAME
     *
     * @param organizationName the value for biz_agency.ORGANIZATION_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_agency.ORGANIZATION_NAME_ABBR
     *
     * @return the value of biz_agency.ORGANIZATION_NAME_ABBR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOrganizationNameAbbr() {
        return organizationNameAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_agency.ORGANIZATION_NAME_ABBR
     *
     * @param organizationNameAbbr the value for biz_agency.ORGANIZATION_NAME_ABBR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrganizationNameAbbr(String organizationNameAbbr) {
        this.organizationNameAbbr = organizationNameAbbr == null ? null : organizationNameAbbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_agency.ADDRESS
     *
     * @return the value of biz_agency.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_agency.ADDRESS
     *
     * @param address the value for biz_agency.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}