package com.yuanchuangyun.libra.model;

public class BizAsicApplicantRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asic_applicant_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asic_applicant_rel.ASIC_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String asicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asic_applicant_rel.APPLICANT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String applicantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asic_applicant_rel.ID
     *
     * @return the value of biz_asic_applicant_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asic_applicant_rel.ID
     *
     * @param id the value for biz_asic_applicant_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asic_applicant_rel.ASIC_ID
     *
     * @return the value of biz_asic_applicant_rel.ASIC_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAsicId() {
        return asicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asic_applicant_rel.ASIC_ID
     *
     * @param asicId the value for biz_asic_applicant_rel.ASIC_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAsicId(String asicId) {
        this.asicId = asicId == null ? null : asicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asic_applicant_rel.APPLICANT_ID
     *
     * @return the value of biz_asic_applicant_rel.APPLICANT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asic_applicant_rel.APPLICANT_ID
     *
     * @param applicantId the value for biz_asic_applicant_rel.APPLICANT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId == null ? null : applicantId.trim();
    }
}