package com.yuanchuangyun.libra.model;

public class BizCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.AREA
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.NAME_ABBR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String nameAbbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.IDENTIFICATION_CARD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String identificationCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.ORGANIZATION_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String organizationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_customer.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String demand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.ID
     *
     * @return the value of biz_customer.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.ID
     *
     * @param id the value for biz_customer.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.AREA
     *
     * @return the value of biz_customer.AREA
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.AREA
     *
     * @param area the value for biz_customer.AREA
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.NAME
     *
     * @return the value of biz_customer.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.NAME
     *
     * @param name the value for biz_customer.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.NAME_ABBR
     *
     * @return the value of biz_customer.NAME_ABBR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getNameAbbr() {
        return nameAbbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.NAME_ABBR
     *
     * @param nameAbbr the value for biz_customer.NAME_ABBR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setNameAbbr(String nameAbbr) {
        this.nameAbbr = nameAbbr == null ? null : nameAbbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.ADDRESS
     *
     * @return the value of biz_customer.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.ADDRESS
     *
     * @param address the value for biz_customer.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.TYPE
     *
     * @return the value of biz_customer.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.TYPE
     *
     * @param type the value for biz_customer.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.IDENTIFICATION_CARD
     *
     * @return the value of biz_customer.IDENTIFICATION_CARD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIdentificationCard() {
        return identificationCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.IDENTIFICATION_CARD
     *
     * @param identificationCard the value for biz_customer.IDENTIFICATION_CARD
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIdentificationCard(String identificationCard) {
        this.identificationCard = identificationCard == null ? null : identificationCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.ORGANIZATION_CODE
     *
     * @return the value of biz_customer.ORGANIZATION_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.ORGANIZATION_CODE
     *
     * @param organizationCode the value for biz_customer.ORGANIZATION_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_customer.DEMAND
     *
     * @return the value of biz_customer.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDemand() {
        return demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_customer.DEMAND
     *
     * @param demand the value for biz_customer.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDemand(String demand) {
        this.demand = demand == null ? null : demand.trim();
    }
}