package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizCase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String whichObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.CASE_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String caseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.STAGES
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String stages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.STAGES_NUM
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String stagesNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.INPUT_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date inputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.REALITY_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String realityAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.GUIDANCE_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String guidanceAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.TITULAR_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String titularAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.FINISH_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String demand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.OPERATER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String operater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_case.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer markDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.ID
     *
     * @return the value of biz_case.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.ID
     *
     * @param id the value for biz_case.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.WHICH_OBJECT
     *
     * @return the value of biz_case.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getWhichObject() {
        return whichObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.WHICH_OBJECT
     *
     * @param whichObject the value for biz_case.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setWhichObject(String whichObject) {
        this.whichObject = whichObject == null ? null : whichObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.OBJECT_ID
     *
     * @return the value of biz_case.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.OBJECT_ID
     *
     * @param objectId the value for biz_case.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.CASE_NUMBER
     *
     * @return the value of biz_case.CASE_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCaseNumber() {
        return caseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.CASE_NUMBER
     *
     * @param caseNumber the value for biz_case.CASE_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber == null ? null : caseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.STAGES
     *
     * @return the value of biz_case.STAGES
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getStages() {
        return stages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.STAGES
     *
     * @param stages the value for biz_case.STAGES
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStages(String stages) {
        this.stages = stages == null ? null : stages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.STAGES_NUM
     *
     * @return the value of biz_case.STAGES_NUM
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getStagesNum() {
        return stagesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.STAGES_NUM
     *
     * @param stagesNum the value for biz_case.STAGES_NUM
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStagesNum(String stagesNum) {
        this.stagesNum = stagesNum == null ? null : stagesNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.INPUT_TIME
     *
     * @return the value of biz_case.INPUT_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.INPUT_TIME
     *
     * @param inputTime the value for biz_case.INPUT_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.REALITY_AGENT
     *
     * @return the value of biz_case.REALITY_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRealityAgent() {
        return realityAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.REALITY_AGENT
     *
     * @param realityAgent the value for biz_case.REALITY_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRealityAgent(String realityAgent) {
        this.realityAgent = realityAgent == null ? null : realityAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.GUIDANCE_AGENT
     *
     * @return the value of biz_case.GUIDANCE_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getGuidanceAgent() {
        return guidanceAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.GUIDANCE_AGENT
     *
     * @param guidanceAgent the value for biz_case.GUIDANCE_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setGuidanceAgent(String guidanceAgent) {
        this.guidanceAgent = guidanceAgent == null ? null : guidanceAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.TITULAR_AGENT
     *
     * @return the value of biz_case.TITULAR_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTitularAgent() {
        return titularAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.TITULAR_AGENT
     *
     * @param titularAgent the value for biz_case.TITULAR_AGENT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTitularAgent(String titularAgent) {
        this.titularAgent = titularAgent == null ? null : titularAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.FINISH_TIME
     *
     * @return the value of biz_case.FINISH_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.FINISH_TIME
     *
     * @param finishTime the value for biz_case.FINISH_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.DEMAND
     *
     * @return the value of biz_case.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDemand() {
        return demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.DEMAND
     *
     * @param demand the value for biz_case.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDemand(String demand) {
        this.demand = demand == null ? null : demand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.OPERATER
     *
     * @return the value of biz_case.OPERATER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOperater() {
        return operater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.OPERATER
     *
     * @param operater the value for biz_case.OPERATER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOperater(String operater) {
        this.operater = operater == null ? null : operater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.CREATION_TIME
     *
     * @return the value of biz_case.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.CREATION_TIME
     *
     * @param creationTime the value for biz_case.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.CREATION_USER_ID
     *
     * @return the value of biz_case.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.CREATION_USER_ID
     *
     * @param creationUserId the value for biz_case.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.LAST_UPDATE_TIME
     *
     * @return the value of biz_case.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for biz_case.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.LAST_UPDATE_USER_ID
     *
     * @return the value of biz_case.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for biz_case.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.DELETE_TIME
     *
     * @return the value of biz_case.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.DELETE_TIME
     *
     * @param deleteTime the value for biz_case.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.DELETE_USER_ID
     *
     * @return the value of biz_case.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.DELETE_USER_ID
     *
     * @param deleteUserId the value for biz_case.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId == null ? null : deleteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_case.MARK_DELETE
     *
     * @return the value of biz_case.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_case.MARK_DELETE
     *
     * @param markDelete the value for biz_case.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }
}