package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizEquivalentApplyNumber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.EQUIVALENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String equivalentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.APPLY_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String applyNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_equivalent_apply_number.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer markDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.ID
     *
     * @return the value of biz_equivalent_apply_number.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.ID
     *
     * @param id the value for biz_equivalent_apply_number.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.EQUIVALENT_ID
     *
     * @return the value of biz_equivalent_apply_number.EQUIVALENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getEquivalentId() {
        return equivalentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.EQUIVALENT_ID
     *
     * @param equivalentId the value for biz_equivalent_apply_number.EQUIVALENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setEquivalentId(String equivalentId) {
        this.equivalentId = equivalentId == null ? null : equivalentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.APPLY_NUMBER
     *
     * @return the value of biz_equivalent_apply_number.APPLY_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getApplyNumber() {
        return applyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.APPLY_NUMBER
     *
     * @param applyNumber the value for biz_equivalent_apply_number.APPLY_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setApplyNumber(String applyNumber) {
        this.applyNumber = applyNumber == null ? null : applyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.CREATION_TIME
     *
     * @return the value of biz_equivalent_apply_number.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.CREATION_TIME
     *
     * @param creationTime the value for biz_equivalent_apply_number.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.CREATION_USER_ID
     *
     * @return the value of biz_equivalent_apply_number.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.CREATION_USER_ID
     *
     * @param creationUserId the value for biz_equivalent_apply_number.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.LAST_UPDATE_TIME
     *
     * @return the value of biz_equivalent_apply_number.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for biz_equivalent_apply_number.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.LAST_UPDATE_USER_ID
     *
     * @return the value of biz_equivalent_apply_number.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for biz_equivalent_apply_number.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.DELETE_TIME
     *
     * @return the value of biz_equivalent_apply_number.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.DELETE_TIME
     *
     * @param deleteTime the value for biz_equivalent_apply_number.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.DELETE_USER_ID
     *
     * @return the value of biz_equivalent_apply_number.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.DELETE_USER_ID
     *
     * @param deleteUserId the value for biz_equivalent_apply_number.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId == null ? null : deleteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_equivalent_apply_number.MARK_DELETE
     *
     * @return the value of biz_equivalent_apply_number.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_equivalent_apply_number.MARK_DELETE
     *
     * @param markDelete the value for biz_equivalent_apply_number.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }
}