package com.yuanchuangyun.libra.model;

public class BizLinkway {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkway.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkway.LINKMAN_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String linkmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkway.WAY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String way;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkway.VAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkway.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkway.ID
     *
     * @return the value of biz_linkway.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkway.ID
     *
     * @param id the value for biz_linkway.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkway.LINKMAN_ID
     *
     * @return the value of biz_linkway.LINKMAN_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLinkmanId() {
        return linkmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkway.LINKMAN_ID
     *
     * @param linkmanId the value for biz_linkway.LINKMAN_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLinkmanId(String linkmanId) {
        this.linkmanId = linkmanId == null ? null : linkmanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkway.WAY
     *
     * @return the value of biz_linkway.WAY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getWay() {
        return way;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkway.WAY
     *
     * @param way the value for biz_linkway.WAY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setWay(String way) {
        this.way = way == null ? null : way.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkway.VAL
     *
     * @return the value of biz_linkway.VAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkway.VAL
     *
     * @param val the value for biz_linkway.VAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkway.REMARK
     *
     * @return the value of biz_linkway.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkway.REMARK
     *
     * @param remark the value for biz_linkway.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}