package com.yuanchuangyun.libra.model;

public class BizLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.IS_DEFAULT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_linkman.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.ID
     *
     * @return the value of biz_linkman.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.ID
     *
     * @param id the value for biz_linkman.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.KIND
     *
     * @return the value of biz_linkman.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.KIND
     *
     * @param kind the value for biz_linkman.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.BUSINESS_ID
     *
     * @return the value of biz_linkman.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.BUSINESS_ID
     *
     * @param businessId the value for biz_linkman.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.NAME
     *
     * @return the value of biz_linkman.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.NAME
     *
     * @param name the value for biz_linkman.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.DUTY
     *
     * @return the value of biz_linkman.DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.DUTY
     *
     * @param duty the value for biz_linkman.DUTY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.ADDRESS
     *
     * @return the value of biz_linkman.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.ADDRESS
     *
     * @param address the value for biz_linkman.ADDRESS
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.IS_DEFAULT
     *
     * @return the value of biz_linkman.IS_DEFAULT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.IS_DEFAULT
     *
     * @param isDefault the value for biz_linkman.IS_DEFAULT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.TYPE
     *
     * @return the value of biz_linkman.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.TYPE
     *
     * @param type the value for biz_linkman.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_linkman.REMARK
     *
     * @return the value of biz_linkman.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_linkman.REMARK
     *
     * @param remark the value for biz_linkman.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}