package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizLawstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String whichObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.INPUT_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.INSTRUCTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String instruction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.LAWSTATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lawstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lawstate.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.ID
     *
     * @return the value of biz_lawstate.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.ID
     *
     * @param id the value for biz_lawstate.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.WHICH_OBJECT
     *
     * @return the value of biz_lawstate.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getWhichObject() {
        return whichObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.WHICH_OBJECT
     *
     * @param whichObject the value for biz_lawstate.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setWhichObject(String whichObject) {
        this.whichObject = whichObject == null ? null : whichObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.OBJECT_ID
     *
     * @return the value of biz_lawstate.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.OBJECT_ID
     *
     * @param objectId the value for biz_lawstate.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.INPUT_DATE
     *
     * @return the value of biz_lawstate.INPUT_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.INPUT_DATE
     *
     * @param inputDate the value for biz_lawstate.INPUT_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.INSTRUCTION
     *
     * @return the value of biz_lawstate.INSTRUCTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.INSTRUCTION
     *
     * @param instruction the value for biz_lawstate.INSTRUCTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.TYPE
     *
     * @return the value of biz_lawstate.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.TYPE
     *
     * @param type the value for biz_lawstate.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.LAWSTATE
     *
     * @return the value of biz_lawstate.LAWSTATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLawstate() {
        return lawstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.LAWSTATE
     *
     * @param lawstate the value for biz_lawstate.LAWSTATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLawstate(String lawstate) {
        this.lawstate = lawstate == null ? null : lawstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.CREATION_TIME
     *
     * @return the value of biz_lawstate.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.CREATION_TIME
     *
     * @param creationTime the value for biz_lawstate.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lawstate.CREATION_USER_ID
     *
     * @return the value of biz_lawstate.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lawstate.CREATION_USER_ID
     *
     * @param creationUserId the value for biz_lawstate.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }
}