package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizObjectCr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.OBLIGEE_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String obligeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.FILING_RIGHTS_CATEGORY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String filingRightsCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.OBLIGEE_COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String obligeeCountryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.RECORD_TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.RECORD_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String recordNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.SIMILAR_GROUP
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String similarGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.PATENT_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String patentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.FILING_START_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date filingStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.FILING_DEADLINE_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date filingDeadlineDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.USE_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String useAttachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.OTHER_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String otherAttachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_cr.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.ID
     *
     * @return the value of biz_object_cr.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.ID
     *
     * @param id the value for biz_object_cr.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.NAME
     *
     * @return the value of biz_object_cr.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.NAME
     *
     * @param name the value for biz_object_cr.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.OBLIGEE_NAME
     *
     * @return the value of biz_object_cr.OBLIGEE_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getObligeeName() {
        return obligeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.OBLIGEE_NAME
     *
     * @param obligeeName the value for biz_object_cr.OBLIGEE_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setObligeeName(String obligeeName) {
        this.obligeeName = obligeeName == null ? null : obligeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.FILING_RIGHTS_CATEGORY
     *
     * @return the value of biz_object_cr.FILING_RIGHTS_CATEGORY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getFilingRightsCategory() {
        return filingRightsCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.FILING_RIGHTS_CATEGORY
     *
     * @param filingRightsCategory the value for biz_object_cr.FILING_RIGHTS_CATEGORY
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setFilingRightsCategory(String filingRightsCategory) {
        this.filingRightsCategory = filingRightsCategory == null ? null : filingRightsCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.OBLIGEE_COUNTRY_ID
     *
     * @return the value of biz_object_cr.OBLIGEE_COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getObligeeCountryId() {
        return obligeeCountryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.OBLIGEE_COUNTRY_ID
     *
     * @param obligeeCountryId the value for biz_object_cr.OBLIGEE_COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setObligeeCountryId(String obligeeCountryId) {
        this.obligeeCountryId = obligeeCountryId == null ? null : obligeeCountryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.RECORD_TYPE
     *
     * @return the value of biz_object_cr.RECORD_TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.RECORD_TYPE
     *
     * @param recordType the value for biz_object_cr.RECORD_TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType == null ? null : recordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.RECORD_NUMBER
     *
     * @return the value of biz_object_cr.RECORD_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRecordNumber() {
        return recordNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.RECORD_NUMBER
     *
     * @param recordNumber the value for biz_object_cr.RECORD_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRecordNumber(String recordNumber) {
        this.recordNumber = recordNumber == null ? null : recordNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.SIMILAR_GROUP
     *
     * @return the value of biz_object_cr.SIMILAR_GROUP
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getSimilarGroup() {
        return similarGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.SIMILAR_GROUP
     *
     * @param similarGroup the value for biz_object_cr.SIMILAR_GROUP
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setSimilarGroup(String similarGroup) {
        this.similarGroup = similarGroup == null ? null : similarGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.PATENT_NUMBER
     *
     * @return the value of biz_object_cr.PATENT_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPatentNumber() {
        return patentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.PATENT_NUMBER
     *
     * @param patentNumber the value for biz_object_cr.PATENT_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPatentNumber(String patentNumber) {
        this.patentNumber = patentNumber == null ? null : patentNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.FILING_START_DATE
     *
     * @return the value of biz_object_cr.FILING_START_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getFilingStartDate() {
        return filingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.FILING_START_DATE
     *
     * @param filingStartDate the value for biz_object_cr.FILING_START_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setFilingStartDate(Date filingStartDate) {
        this.filingStartDate = filingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.FILING_DEADLINE_DATE
     *
     * @return the value of biz_object_cr.FILING_DEADLINE_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getFilingDeadlineDate() {
        return filingDeadlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.FILING_DEADLINE_DATE
     *
     * @param filingDeadlineDate the value for biz_object_cr.FILING_DEADLINE_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setFilingDeadlineDate(Date filingDeadlineDate) {
        this.filingDeadlineDate = filingDeadlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.USE_ATTACH_ID
     *
     * @return the value of biz_object_cr.USE_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getUseAttachId() {
        return useAttachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.USE_ATTACH_ID
     *
     * @param useAttachId the value for biz_object_cr.USE_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setUseAttachId(String useAttachId) {
        this.useAttachId = useAttachId == null ? null : useAttachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.OTHER_ATTACH_ID
     *
     * @return the value of biz_object_cr.OTHER_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOtherAttachId() {
        return otherAttachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.OTHER_ATTACH_ID
     *
     * @param otherAttachId the value for biz_object_cr.OTHER_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOtherAttachId(String otherAttachId) {
        this.otherAttachId = otherAttachId == null ? null : otherAttachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_cr.REMARK
     *
     * @return the value of biz_object_cr.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_cr.REMARK
     *
     * @param remark the value for biz_object_cr.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}