package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizObjectCopyright {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.REGISTER_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String registerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.REGISTER_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.IS_PUBLISHED
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer isPublished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.FIRST_PUBLISH_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date firstPublishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.FINISH_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.AUTHOR_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String authorCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.AUTHOR_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String authorEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.AUTHOR_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String authorOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.USE_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String useAttachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.OTHER_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String otherAttachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_copyright.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.ID
     *
     * @return the value of biz_object_copyright.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.ID
     *
     * @param id the value for biz_object_copyright.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.NAME
     *
     * @return the value of biz_object_copyright.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.NAME
     *
     * @param name the value for biz_object_copyright.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.TYPE
     *
     * @return the value of biz_object_copyright.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.TYPE
     *
     * @param type the value for biz_object_copyright.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.REGISTER_NUMBER
     *
     * @return the value of biz_object_copyright.REGISTER_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRegisterNumber() {
        return registerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.REGISTER_NUMBER
     *
     * @param registerNumber the value for biz_object_copyright.REGISTER_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRegisterNumber(String registerNumber) {
        this.registerNumber = registerNumber == null ? null : registerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.REGISTER_DATE
     *
     * @return the value of biz_object_copyright.REGISTER_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.REGISTER_DATE
     *
     * @param registerDate the value for biz_object_copyright.REGISTER_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.IS_PUBLISHED
     *
     * @return the value of biz_object_copyright.IS_PUBLISHED
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getIsPublished() {
        return isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.IS_PUBLISHED
     *
     * @param isPublished the value for biz_object_copyright.IS_PUBLISHED
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIsPublished(Integer isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.FIRST_PUBLISH_DATE
     *
     * @return the value of biz_object_copyright.FIRST_PUBLISH_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getFirstPublishDate() {
        return firstPublishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.FIRST_PUBLISH_DATE
     *
     * @param firstPublishDate the value for biz_object_copyright.FIRST_PUBLISH_DATE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setFirstPublishDate(Date firstPublishDate) {
        this.firstPublishDate = firstPublishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.FINISH_TIME
     *
     * @return the value of biz_object_copyright.FINISH_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.FINISH_TIME
     *
     * @param finishTime the value for biz_object_copyright.FINISH_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.AUTHOR_CH
     *
     * @return the value of biz_object_copyright.AUTHOR_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAuthorCh() {
        return authorCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.AUTHOR_CH
     *
     * @param authorCh the value for biz_object_copyright.AUTHOR_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAuthorCh(String authorCh) {
        this.authorCh = authorCh == null ? null : authorCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.AUTHOR_EN
     *
     * @return the value of biz_object_copyright.AUTHOR_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAuthorEn() {
        return authorEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.AUTHOR_EN
     *
     * @param authorEn the value for biz_object_copyright.AUTHOR_EN
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAuthorEn(String authorEn) {
        this.authorEn = authorEn == null ? null : authorEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.AUTHOR_ORIGINAL
     *
     * @return the value of biz_object_copyright.AUTHOR_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAuthorOriginal() {
        return authorOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.AUTHOR_ORIGINAL
     *
     * @param authorOriginal the value for biz_object_copyright.AUTHOR_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAuthorOriginal(String authorOriginal) {
        this.authorOriginal = authorOriginal == null ? null : authorOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.USE_ATTACH_ID
     *
     * @return the value of biz_object_copyright.USE_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getUseAttachId() {
        return useAttachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.USE_ATTACH_ID
     *
     * @param useAttachId the value for biz_object_copyright.USE_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setUseAttachId(String useAttachId) {
        this.useAttachId = useAttachId == null ? null : useAttachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.OTHER_ATTACH_ID
     *
     * @return the value of biz_object_copyright.OTHER_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOtherAttachId() {
        return otherAttachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.OTHER_ATTACH_ID
     *
     * @param otherAttachId the value for biz_object_copyright.OTHER_ATTACH_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOtherAttachId(String otherAttachId) {
        this.otherAttachId = otherAttachId == null ? null : otherAttachId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_copyright.REMARK
     *
     * @return the value of biz_object_copyright.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_copyright.REMARK
     *
     * @param remark the value for biz_object_copyright.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}