package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizObjectManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String trackCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String styleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.Column_5
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String column5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.OBJECT_GROUP_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String objectGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.INSTRUCTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String instruction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_object_manage.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.ID
     *
     * @return the value of biz_object_manage.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.ID
     *
     * @param id the value for biz_object_manage.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.TRACK_CODE
     *
     * @return the value of biz_object_manage.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTrackCode() {
        return trackCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.TRACK_CODE
     *
     * @param trackCode the value for biz_object_manage.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTrackCode(String trackCode) {
        this.trackCode = trackCode == null ? null : trackCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.STYLE_CODE
     *
     * @return the value of biz_object_manage.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getStyleCode() {
        return styleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.STYLE_CODE
     *
     * @param styleCode the value for biz_object_manage.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStyleCode(String styleCode) {
        this.styleCode = styleCode == null ? null : styleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.Column_5
     *
     * @return the value of biz_object_manage.Column_5
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getColumn5() {
        return column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.Column_5
     *
     * @param column5 the value for biz_object_manage.Column_5
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setColumn5(String column5) {
        this.column5 = column5 == null ? null : column5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.OBJECT_GROUP_CODE
     *
     * @return the value of biz_object_manage.OBJECT_GROUP_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getObjectGroupCode() {
        return objectGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.OBJECT_GROUP_CODE
     *
     * @param objectGroupCode the value for biz_object_manage.OBJECT_GROUP_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setObjectGroupCode(String objectGroupCode) {
        this.objectGroupCode = objectGroupCode == null ? null : objectGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.INSTRUCTION
     *
     * @return the value of biz_object_manage.INSTRUCTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.INSTRUCTION
     *
     * @param instruction the value for biz_object_manage.INSTRUCTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.CREATION_TIME
     *
     * @return the value of biz_object_manage.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.CREATION_TIME
     *
     * @param creationTime the value for biz_object_manage.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_object_manage.CREATION_USER_ID
     *
     * @return the value of biz_object_manage.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_object_manage.CREATION_USER_ID
     *
     * @param creationUserId the value for biz_object_manage.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }
}