package com.yuanchuangyun.libra.model;

public class BizPriorityPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_priority_person.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_priority_person.PRIORITY_INFO_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String priorityInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_priority_person.PRIORITY_PERSON_NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String priorityPersonNameCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_priority_person.PRIORITY_PERSON_NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String priorityPersonNameOriginal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_priority_person.ID
     *
     * @return the value of biz_priority_person.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_priority_person.ID
     *
     * @param id the value for biz_priority_person.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_priority_person.PRIORITY_INFO_ID
     *
     * @return the value of biz_priority_person.PRIORITY_INFO_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPriorityInfoId() {
        return priorityInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_priority_person.PRIORITY_INFO_ID
     *
     * @param priorityInfoId the value for biz_priority_person.PRIORITY_INFO_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPriorityInfoId(String priorityInfoId) {
        this.priorityInfoId = priorityInfoId == null ? null : priorityInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_priority_person.PRIORITY_PERSON_NAME_CH
     *
     * @return the value of biz_priority_person.PRIORITY_PERSON_NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPriorityPersonNameCh() {
        return priorityPersonNameCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_priority_person.PRIORITY_PERSON_NAME_CH
     *
     * @param priorityPersonNameCh the value for biz_priority_person.PRIORITY_PERSON_NAME_CH
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPriorityPersonNameCh(String priorityPersonNameCh) {
        this.priorityPersonNameCh = priorityPersonNameCh == null ? null : priorityPersonNameCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_priority_person.PRIORITY_PERSON_NAME_ORIGINAL
     *
     * @return the value of biz_priority_person.PRIORITY_PERSON_NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPriorityPersonNameOriginal() {
        return priorityPersonNameOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_priority_person.PRIORITY_PERSON_NAME_ORIGINAL
     *
     * @param priorityPersonNameOriginal the value for biz_priority_person.PRIORITY_PERSON_NAME_ORIGINAL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPriorityPersonNameOriginal(String priorityPersonNameOriginal) {
        this.priorityPersonNameOriginal = priorityPersonNameOriginal == null ? null : priorityPersonNameOriginal.trim();
    }
}