package com.yuanchuangyun.libra.model;

import java.math.BigDecimal;

public class BizPayRuler {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String trackCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String styleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.STAGES
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String stages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.AMOUNT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ruler.LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.ID
     *
     * @return the value of biz_pay_ruler.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.ID
     *
     * @param id the value for biz_pay_ruler.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.KIND
     *
     * @return the value of biz_pay_ruler.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.KIND
     *
     * @param kind the value for biz_pay_ruler.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.BUSINESS_ID
     *
     * @return the value of biz_pay_ruler.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.BUSINESS_ID
     *
     * @param businessId the value for biz_pay_ruler.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.TYPE
     *
     * @return the value of biz_pay_ruler.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.TYPE
     *
     * @param type the value for biz_pay_ruler.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.TRACK_CODE
     *
     * @return the value of biz_pay_ruler.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTrackCode() {
        return trackCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.TRACK_CODE
     *
     * @param trackCode the value for biz_pay_ruler.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTrackCode(String trackCode) {
        this.trackCode = trackCode == null ? null : trackCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.STYLE_CODE
     *
     * @return the value of biz_pay_ruler.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getStyleCode() {
        return styleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.STYLE_CODE
     *
     * @param styleCode the value for biz_pay_ruler.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStyleCode(String styleCode) {
        this.styleCode = styleCode == null ? null : styleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.STAGES
     *
     * @return the value of biz_pay_ruler.STAGES
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getStages() {
        return stages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.STAGES
     *
     * @param stages the value for biz_pay_ruler.STAGES
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStages(String stages) {
        this.stages = stages == null ? null : stages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.AMOUNT
     *
     * @return the value of biz_pay_ruler.AMOUNT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.AMOUNT
     *
     * @param amount the value for biz_pay_ruler.AMOUNT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.REMARK
     *
     * @return the value of biz_pay_ruler.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.REMARK
     *
     * @param remark the value for biz_pay_ruler.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ruler.LOCATION
     *
     * @return the value of biz_pay_ruler.LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ruler.LOCATION
     *
     * @param location the value for biz_pay_ruler.LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}