package com.yuanchuangyun.libra.model;

public class BizPatentSpecifiedCountry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_patent_specified_country.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_patent_specified_country.PATENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String patentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_patent_specified_country.COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String countryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_patent_specified_country.ID
     *
     * @return the value of biz_patent_specified_country.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_patent_specified_country.ID
     *
     * @param id the value for biz_patent_specified_country.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_patent_specified_country.PATENT_ID
     *
     * @return the value of biz_patent_specified_country.PATENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getPatentId() {
        return patentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_patent_specified_country.PATENT_ID
     *
     * @param patentId the value for biz_patent_specified_country.PATENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setPatentId(String patentId) {
        this.patentId = patentId == null ? null : patentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_patent_specified_country.COUNTRY_ID
     *
     * @return the value of biz_patent_specified_country.COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_patent_specified_country.COUNTRY_ID
     *
     * @param countryId the value for biz_patent_specified_country.COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }
}