package com.yuanchuangyun.libra.model;

import java.util.Date;

public class BizProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.PROJECT_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String projectNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.CUSTOMER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.CUSTOMER_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String customerNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.ORGANIZATION_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String organizationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String trackCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String styleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.YEAR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.SERIES_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String seriesNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String creationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String deleteUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer markDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.ID
     *
     * @return the value of biz_project.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.ID
     *
     * @param id the value for biz_project.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.PROJECT_NUMBER
     *
     * @return the value of biz_project.PROJECT_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getProjectNumber() {
        return projectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.PROJECT_NUMBER
     *
     * @param projectNumber the value for biz_project.PROJECT_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber == null ? null : projectNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.NAME
     *
     * @return the value of biz_project.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.NAME
     *
     * @param name the value for biz_project.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.CUSTOMER_ID
     *
     * @return the value of biz_project.CUSTOMER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.CUSTOMER_ID
     *
     * @param customerId the value for biz_project.CUSTOMER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.CUSTOMER_NUMBER
     *
     * @return the value of biz_project.CUSTOMER_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.CUSTOMER_NUMBER
     *
     * @param customerNumber the value for biz_project.CUSTOMER_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber == null ? null : customerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.ORGANIZATION_NUMBER
     *
     * @return the value of biz_project.ORGANIZATION_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getOrganizationNumber() {
        return organizationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.ORGANIZATION_NUMBER
     *
     * @param organizationNumber the value for biz_project.ORGANIZATION_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrganizationNumber(String organizationNumber) {
        this.organizationNumber = organizationNumber == null ? null : organizationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.TRACK_CODE
     *
     * @return the value of biz_project.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTrackCode() {
        return trackCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.TRACK_CODE
     *
     * @param trackCode the value for biz_project.TRACK_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTrackCode(String trackCode) {
        this.trackCode = trackCode == null ? null : trackCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.STYLE_CODE
     *
     * @return the value of biz_project.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getStyleCode() {
        return styleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.STYLE_CODE
     *
     * @param styleCode the value for biz_project.STYLE_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setStyleCode(String styleCode) {
        this.styleCode = styleCode == null ? null : styleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.YEAR
     *
     * @return the value of biz_project.YEAR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.YEAR
     *
     * @param year the value for biz_project.YEAR
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.SERIES_NUMBER
     *
     * @return the value of biz_project.SERIES_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.SERIES_NUMBER
     *
     * @param seriesNumber the value for biz_project.SERIES_NUMBER
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setSeriesNumber(String seriesNumber) {
        this.seriesNumber = seriesNumber == null ? null : seriesNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.REMARK
     *
     * @return the value of biz_project.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.REMARK
     *
     * @param remark the value for biz_project.REMARK
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.CREATION_TIME
     *
     * @return the value of biz_project.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.CREATION_TIME
     *
     * @param creationTime the value for biz_project.CREATION_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.CREATION_USER_ID
     *
     * @return the value of biz_project.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.CREATION_USER_ID
     *
     * @param creationUserId the value for biz_project.CREATION_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.LAST_UPDATE_TIME
     *
     * @return the value of biz_project.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for biz_project.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.LAST_UPDATE_USER_ID
     *
     * @return the value of biz_project.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for biz_project.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.DELETE_TIME
     *
     * @return the value of biz_project.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.DELETE_TIME
     *
     * @param deleteTime the value for biz_project.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.DELETE_USER_ID
     *
     * @return the value of biz_project.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDeleteUserId() {
        return deleteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.DELETE_USER_ID
     *
     * @param deleteUserId the value for biz_project.DELETE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteUserId(String deleteUserId) {
        this.deleteUserId = deleteUserId == null ? null : deleteUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.MARK_DELETE
     *
     * @return the value of biz_project.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.MARK_DELETE
     *
     * @param markDelete the value for biz_project.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMarkDelete(Integer markDelete) {
        this.markDelete = markDelete;
    }
}