package com.yuanchuangyun.libra.model;

public class BizPayAsk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ask.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ask.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ask.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ask.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ask.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String demand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pay_ask.LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ask.ID
     *
     * @return the value of biz_pay_ask.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ask.ID
     *
     * @param id the value for biz_pay_ask.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ask.KIND
     *
     * @return the value of biz_pay_ask.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ask.KIND
     *
     * @param kind the value for biz_pay_ask.KIND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ask.BUSINESS_ID
     *
     * @return the value of biz_pay_ask.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ask.BUSINESS_ID
     *
     * @param businessId the value for biz_pay_ask.BUSINESS_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ask.NAME
     *
     * @return the value of biz_pay_ask.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ask.NAME
     *
     * @param name the value for biz_pay_ask.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ask.DEMAND
     *
     * @return the value of biz_pay_ask.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDemand() {
        return demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ask.DEMAND
     *
     * @param demand the value for biz_pay_ask.DEMAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDemand(String demand) {
        this.demand = demand == null ? null : demand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pay_ask.LOCATION
     *
     * @return the value of biz_pay_ask.LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pay_ask.LOCATION
     *
     * @param location the value for biz_pay_ask.LOCATION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }
}