package com.yuanchuangyun.libra.model;

public class BizTrademarkApplicantRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_applicant_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_applicant_rel.TRADEMARK_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String trademarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_applicant_rel.APPLICANT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String applicantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_applicant_rel.ID
     *
     * @return the value of biz_trademark_applicant_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_applicant_rel.ID
     *
     * @param id the value for biz_trademark_applicant_rel.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_applicant_rel.TRADEMARK_ID
     *
     * @return the value of biz_trademark_applicant_rel.TRADEMARK_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTrademarkId() {
        return trademarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_applicant_rel.TRADEMARK_ID
     *
     * @param trademarkId the value for biz_trademark_applicant_rel.TRADEMARK_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTrademarkId(String trademarkId) {
        this.trademarkId = trademarkId == null ? null : trademarkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_applicant_rel.APPLICANT_ID
     *
     * @return the value of biz_trademark_applicant_rel.APPLICANT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_applicant_rel.APPLICANT_ID
     *
     * @param applicantId the value for biz_trademark_applicant_rel.APPLICANT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId == null ? null : applicantId.trim();
    }
}