package com.yuanchuangyun.libra.model;

public class BizTrademarkSpecifiedCountry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_specified_country.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_specified_country.TRADEMARK_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String trademarkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_specified_country.COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_trademark_specified_country.IS_LATE_SPECIFIED
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String isLateSpecified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_specified_country.ID
     *
     * @return the value of biz_trademark_specified_country.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_specified_country.ID
     *
     * @param id the value for biz_trademark_specified_country.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_specified_country.TRADEMARK_ID
     *
     * @return the value of biz_trademark_specified_country.TRADEMARK_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getTrademarkId() {
        return trademarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_specified_country.TRADEMARK_ID
     *
     * @param trademarkId the value for biz_trademark_specified_country.TRADEMARK_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setTrademarkId(String trademarkId) {
        this.trademarkId = trademarkId == null ? null : trademarkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_specified_country.COUNTRY_ID
     *
     * @return the value of biz_trademark_specified_country.COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_specified_country.COUNTRY_ID
     *
     * @param countryId the value for biz_trademark_specified_country.COUNTRY_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_trademark_specified_country.IS_LATE_SPECIFIED
     *
     * @return the value of biz_trademark_specified_country.IS_LATE_SPECIFIED
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIsLateSpecified() {
        return isLateSpecified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_trademark_specified_country.IS_LATE_SPECIFIED
     *
     * @param isLateSpecified the value for biz_trademark_specified_country.IS_LATE_SPECIFIED
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIsLateSpecified(String isLateSpecified) {
        this.isLateSpecified = isLateSpecified == null ? null : isLateSpecified.trim();
    }
}