package com.yuanchuangyun.libra.model;

public class BizTechLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String whichObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.IPR_CUSTOMER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String iprCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.MOBILE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tech_linkman.EMAIL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.ID
     *
     * @return the value of biz_tech_linkman.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.ID
     *
     * @param id the value for biz_tech_linkman.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.WHICH_OBJECT
     *
     * @return the value of biz_tech_linkman.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getWhichObject() {
        return whichObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.WHICH_OBJECT
     *
     * @param whichObject the value for biz_tech_linkman.WHICH_OBJECT
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setWhichObject(String whichObject) {
        this.whichObject = whichObject == null ? null : whichObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.OBJECT_ID
     *
     * @return the value of biz_tech_linkman.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.OBJECT_ID
     *
     * @param objectId the value for biz_tech_linkman.OBJECT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.IPR_CUSTOMER_ID
     *
     * @return the value of biz_tech_linkman.IPR_CUSTOMER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIprCustomerId() {
        return iprCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.IPR_CUSTOMER_ID
     *
     * @param iprCustomerId the value for biz_tech_linkman.IPR_CUSTOMER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIprCustomerId(String iprCustomerId) {
        this.iprCustomerId = iprCustomerId == null ? null : iprCustomerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.NAME
     *
     * @return the value of biz_tech_linkman.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.NAME
     *
     * @param name the value for biz_tech_linkman.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.MOBILE
     *
     * @return the value of biz_tech_linkman.MOBILE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.MOBILE
     *
     * @param mobile the value for biz_tech_linkman.MOBILE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tech_linkman.EMAIL
     *
     * @return the value of biz_tech_linkman.EMAIL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tech_linkman.EMAIL
     *
     * @param email the value for biz_tech_linkman.EMAIL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}