package com.yuanchuangyun.libra.model;

public class PfDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_dict.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_dict.DICT_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_dict.DICT_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_dict.DICT_VALUE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_dict.DICT_PID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer dictPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_dict.ID
     *
     * @return the value of pf_dict.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_dict.ID
     *
     * @param id the value for pf_dict.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_dict.DICT_NAME
     *
     * @return the value of pf_dict.DICT_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_dict.DICT_NAME
     *
     * @param dictName the value for pf_dict.DICT_NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_dict.DICT_CODE
     *
     * @return the value of pf_dict.DICT_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_dict.DICT_CODE
     *
     * @param dictCode the value for pf_dict.DICT_CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_dict.DICT_VALUE
     *
     * @return the value of pf_dict.DICT_VALUE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_dict.DICT_VALUE
     *
     * @param dictValue the value for pf_dict.DICT_VALUE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_dict.DICT_PID
     *
     * @return the value of pf_dict.DICT_PID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getDictPid() {
        return dictPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_dict.DICT_PID
     *
     * @param dictPid the value for pf_dict.DICT_PID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDictPid(Integer dictPid) {
        this.dictPid = dictPid;
    }
}