package com.yuanchuangyun.libra.model;

import java.util.Date;

public class PfPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.IS_MENU
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String isMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.URL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.ALLOW_EXPAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String allowExpand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.ICON
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.PARENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.CREATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.CREATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String markDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_permission.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.ID
     *
     * @return the value of pf_permission.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.ID
     *
     * @param id the value for pf_permission.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.NAME
     *
     * @return the value of pf_permission.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.NAME
     *
     * @param name the value for pf_permission.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.CODE
     *
     * @return the value of pf_permission.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.CODE
     *
     * @param code the value for pf_permission.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.IS_MENU
     *
     * @return the value of pf_permission.IS_MENU
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.IS_MENU
     *
     * @param isMenu the value for pf_permission.IS_MENU
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIsMenu(String isMenu) {
        this.isMenu = isMenu == null ? null : isMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.URL
     *
     * @return the value of pf_permission.URL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.URL
     *
     * @param url the value for pf_permission.URL
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.ALLOW_EXPAND
     *
     * @return the value of pf_permission.ALLOW_EXPAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getAllowExpand() {
        return allowExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.ALLOW_EXPAND
     *
     * @param allowExpand the value for pf_permission.ALLOW_EXPAND
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setAllowExpand(String allowExpand) {
        this.allowExpand = allowExpand == null ? null : allowExpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.ICON
     *
     * @return the value of pf_permission.ICON
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.ICON
     *
     * @param icon the value for pf_permission.ICON
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.DESCRIPTION
     *
     * @return the value of pf_permission.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.DESCRIPTION
     *
     * @param description the value for pf_permission.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.PARENT_ID
     *
     * @return the value of pf_permission.PARENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.PARENT_ID
     *
     * @param parentId the value for pf_permission.PARENT_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.CREATE_TIME
     *
     * @return the value of pf_permission.CREATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.CREATE_TIME
     *
     * @param createTime the value for pf_permission.CREATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.CREATE_USER_ID
     *
     * @return the value of pf_permission.CREATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.CREATE_USER_ID
     *
     * @param createUserId the value for pf_permission.CREATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.DELETE_TIME
     *
     * @return the value of pf_permission.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.DELETE_TIME
     *
     * @param deleteTime the value for pf_permission.DELETE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.LAST_UPDATE_TIME
     *
     * @return the value of pf_permission.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for pf_permission.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.LAST_UPDATE_USER_ID
     *
     * @return the value of pf_permission.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for pf_permission.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.MARK_DELETE
     *
     * @return the value of pf_permission.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.MARK_DELETE
     *
     * @param markDelete the value for pf_permission.MARK_DELETE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMarkDelete(String markDelete) {
        this.markDelete = markDelete == null ? null : markDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_permission.ORDER_NO
     *
     * @return the value of pf_permission.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_permission.ORDER_NO
     *
     * @param orderNo the value for pf_permission.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}