package com.yuanchuangyun.libra.model;

import java.util.Date;

public class PfRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.MAPPER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String mapperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.CREATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.CREATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pf_role.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    private String lastUpdateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.ID
     *
     * @return the value of pf_role.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.ID
     *
     * @param id the value for pf_role.ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.CODE
     *
     * @return the value of pf_role.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.CODE
     *
     * @param code the value for pf_role.CODE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.NAME
     *
     * @return the value of pf_role.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.NAME
     *
     * @param name the value for pf_role.NAME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.TYPE
     *
     * @return the value of pf_role.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.TYPE
     *
     * @param type the value for pf_role.TYPE
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.MAPPER_ID
     *
     * @return the value of pf_role.MAPPER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getMapperId() {
        return mapperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.MAPPER_ID
     *
     * @param mapperId the value for pf_role.MAPPER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setMapperId(String mapperId) {
        this.mapperId = mapperId == null ? null : mapperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.DESCRIPTION
     *
     * @return the value of pf_role.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.DESCRIPTION
     *
     * @param description the value for pf_role.DESCRIPTION
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.ORDER_NO
     *
     * @return the value of pf_role.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.ORDER_NO
     *
     * @param orderNo the value for pf_role.ORDER_NO
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.CREATE_TIME
     *
     * @return the value of pf_role.CREATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.CREATE_TIME
     *
     * @param createTime the value for pf_role.CREATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.CREATE_USER_ID
     *
     * @return the value of pf_role.CREATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.CREATE_USER_ID
     *
     * @param createUserId the value for pf_role.CREATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.LAST_UPDATE_TIME
     *
     * @return the value of pf_role.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for pf_role.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pf_role.LAST_UPDATE_USER_ID
     *
     * @return the value of pf_role.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pf_role.LAST_UPDATE_USER_ID
     *
     * @param lastUpdateUserId the value for pf_role.LAST_UPDATE_USER_ID
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }
}