package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseUserRoleRel;

public interface BaseUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseUserRoleRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseUserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseUserRoleRel record);
}