package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseResource;

public interface BaseResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseResource record);
}