package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseUserTagRel;

public interface BaseUserTagRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_tag_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_tag_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseUserTagRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_tag_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseUserTagRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_tag_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseUserTagRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_tag_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseUserTagRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_tag_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseUserTagRel record);
}