package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseConfig;

public interface BaseConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_config
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseConfig record);
}