package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseTag;

public interface BaseTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseTag selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_tag
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseTag record);
}