package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseDepartment;

public interface BaseDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_department
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_department
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_department
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_department
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_department
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_department
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseDepartment record);
}