package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BaseDictValue;

public interface BaseDictValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict_value
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict_value
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BaseDictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict_value
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BaseDictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict_value
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BaseDictValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict_value
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BaseDictValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict_value
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BaseDictValue record);
}