package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BasePermissionResourceRel;

public interface BasePermissionResourceRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission_resource_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission_resource_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BasePermissionResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission_resource_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BasePermissionResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission_resource_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BasePermissionResourceRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission_resource_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BasePermissionResourceRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_permission_resource_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BasePermissionResourceRel record);
}