package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizAsicApplicantRel;

public interface BizAsicApplicantRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_asic_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_asic_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizAsicApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_asic_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizAsicApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_asic_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizAsicApplicantRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_asic_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizAsicApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_asic_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizAsicApplicantRel record);
}