package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizApplicant;

public interface BizApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_applicant
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_applicant
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_applicant
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_applicant
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizApplicant selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_applicant
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_applicant
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizApplicant record);
}