package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizAgency;

public interface BizAgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_agency
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_agency
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_agency
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_agency
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizAgency selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_agency
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_agency
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizAgency record);
}