package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizContract;

public interface BizContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_contract
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_contract
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_contract
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_contract
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizContract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_contract
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_contract
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizContract record);
}