package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizCase;

public interface BizCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_case
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_case
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_case
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_case
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizCase selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_case
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizCase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_case
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizCase record);
}