package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizEquivalent;

public interface BizEquivalentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizEquivalent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizEquivalent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizEquivalent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizEquivalent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizEquivalent record);
}