package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizEquivalentApplyNumber;

public interface BizEquivalentApplyNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent_apply_number
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent_apply_number
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizEquivalentApplyNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent_apply_number
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizEquivalentApplyNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent_apply_number
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizEquivalentApplyNumber selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent_apply_number
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizEquivalentApplyNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_equivalent_apply_number
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizEquivalentApplyNumber record);
}