package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizFileModel;

public interface BizFileModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file_model
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file_model
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file_model
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file_model
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizFileModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file_model
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_file_model
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizFileModel record);
}