package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizInventor;

public interface BizInventorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_inventor
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_inventor
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizInventor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_inventor
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizInventor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_inventor
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizInventor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_inventor
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizInventor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_inventor
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizInventor record);
}