package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizLinkway;

public interface BizLinkwayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_linkway
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_linkway
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizLinkway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_linkway
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizLinkway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_linkway
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizLinkway selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_linkway
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizLinkway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_linkway
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizLinkway record);
}