package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizLawstate;

public interface BizLawstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lawstate
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lawstate
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizLawstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lawstate
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizLawstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lawstate
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizLawstate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lawstate
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizLawstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lawstate
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizLawstate record);
}