package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizMenu;

public interface BizMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_menu
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_menu
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_menu
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_menu
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_menu
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_menu
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizMenu record);
}