package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizObjectGroup;

public interface BizObjectGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_group
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizObjectGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_group
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizObjectGroup record);
}