package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizObjectTrademark;

public interface BizObjectTrademarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_trademark
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_trademark
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizObjectTrademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_trademark
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizObjectTrademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_trademark
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizObjectTrademark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_trademark
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizObjectTrademark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_trademark
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizObjectTrademark record);
}