package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizObjectConsult;

public interface BizObjectConsultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_consult
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_consult
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizObjectConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_consult
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizObjectConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_consult
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizObjectConsult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_consult
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizObjectConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_consult
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizObjectConsult record);
}