package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizObjectPatent;

public interface BizObjectPatentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_patent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_patent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizObjectPatent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_patent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizObjectPatent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_patent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizObjectPatent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_patent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizObjectPatent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_object_patent
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizObjectPatent record);
}