package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizProjectAgencyRel;

public interface BizProjectAgencyRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project_agency_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project_agency_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizProjectAgencyRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project_agency_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizProjectAgencyRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project_agency_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizProjectAgencyRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project_agency_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizProjectAgencyRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project_agency_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizProjectAgencyRel record);
}