package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizPayRuler;

public interface BizPayRulerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ruler
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ruler
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizPayRuler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ruler
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizPayRuler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ruler
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizPayRuler selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ruler
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizPayRuler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ruler
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizPayRuler record);
}