package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizPriorityInfo;

public interface BizPriorityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_priority_info
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_priority_info
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizPriorityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_priority_info
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizPriorityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_priority_info
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizPriorityInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_priority_info
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizPriorityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_priority_info
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizPriorityInfo record);
}