package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizPayAsk;

public interface BizPayAskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ask
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ask
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizPayAsk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ask
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizPayAsk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ask
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizPayAsk selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ask
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizPayAsk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_pay_ask
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizPayAsk record);
}