package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizPatentApplicantRel;

public interface BizPatentApplicantRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizPatentApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizPatentApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizPatentApplicantRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizPatentApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizPatentApplicantRel record);
}