package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizProject;

public interface BizProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_project
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizProject record);
}