package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizPatentSpecifiedCountry;

public interface BizPatentSpecifiedCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizPatentSpecifiedCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizPatentSpecifiedCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizPatentSpecifiedCountry selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizPatentSpecifiedCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_patent_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizPatentSpecifiedCountry record);
}