package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizTrademarkApplicantRel;

public interface BizTrademarkApplicantRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizTrademarkApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizTrademarkApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizTrademarkApplicantRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizTrademarkApplicantRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_applicant_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizTrademarkApplicantRel record);
}