package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizTrack;

public interface BizTrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_track
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizTrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_track
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizTrack record);
}