package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizTrademarkSpecifiedCountry;

public interface BizTrademarkSpecifiedCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizTrademarkSpecifiedCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizTrademarkSpecifiedCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizTrademarkSpecifiedCountry selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizTrademarkSpecifiedCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_trademark_specified_country
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizTrademarkSpecifiedCountry record);
}