package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.BizUserFiles;

public interface BizUserFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_files
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_files
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(BizUserFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_files
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(BizUserFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_files
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    BizUserFiles selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_files
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(BizUserFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user_files
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(BizUserFiles record);
}