package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.PfPermission;

public interface PfPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_permission
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_permission
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(PfPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_permission
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(PfPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_permission
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    PfPermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_permission
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(PfPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_permission
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(PfPermission record);
}