package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.PfResourcePermissionRelKey;

public interface PfResourcePermissionRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource_permission_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(PfResourcePermissionRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource_permission_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(PfResourcePermissionRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource_permission_rel
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(PfResourcePermissionRelKey record);
}