package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.PfResource;

public interface PfResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(PfResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(PfResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    PfResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(PfResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_resource
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(PfResource record);
}