package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.PfRole;

public interface PfRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_role
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_role
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(PfRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_role
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(PfRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_role
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    PfRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_role
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(PfRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_role
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(PfRole record);
}