package com.yuanchuangyun.libra.dao;

import com.yuanchuangyun.libra.model.PfUser;

public interface PfUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_user
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_user
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insert(PfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_user
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int insertSelective(PfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_user
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    PfUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_user
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKeySelective(PfUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pf_user
     *
     * @mbg.generated Wed Oct 19 17:51:59 CST 2016
     */
    int updateByPrimaryKey(PfUser record);
}